# Generated by Django 2.2 on 2019-04-24 19:10

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0002_auto_20190423_2059'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profile',
            name='rok',
            field=models.IntegerField(blank=True, null=True, validators=[django.core.validators.MaxValueValidator(4), django.core.validators.MinValueValidator(1)]),
        ),
    ]
