# Generated by Django 2.2 on 2019-06-05 17:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0003_auto_20190424_2110'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profile',
            name='uczelnia',
            field=models.CharField(choices=[('Brak uczelni', 'Brak uczelni'), ('Politechnika Rzeszowska', 'Politechnika Rzeszowska'), ('Uniwersytet Rzeszowski', 'Uniwersytet Rzeszowski'), ('Inna uczelnia', 'Inna uczelnia')], default='Brak uczelni', max_length=40),
        ),
    ]
