# Generated by Django 2.2 on 2019-06-20 19:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('odnosniki', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='odnosnik',
            name='image',
            field=models.ImageField(upload_to='odnosniki_pics'),
        ),
    ]
