# Generated by Django 2.2 on 2019-07-02 20:17

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Powiadomienie',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nazwa', models.CharField(max_length=100)),
                ('treść', models.TextField()),
                ('date_posted', models.DateTimeField(default=django.utils.timezone.now)),
                ('kategoria', models.CharField(choices=[('testowe', 'testowe'), ('Przypomnienie o wydarzeniu', 'Przypomnienia'), ('Ważne informacje', 'Ważne'), ('Konkursy', 'Konkurs'), ('Inne', 'Inne')], default='testowe', max_length=40)),
                ('odbiorcy', models.CharField(choices=[('wszyscy', 'Wszyscy'), ('Brak uczelni', 'Brak uczelni'), ('Politechnika Rzeszowska', 'Politechnika Rzeszowska'), ('Uniwersytet Rzeszowski', 'Uniwersytet Rzeszowski'), ('Inna uczelnia', 'Inna uczelnia')], default='Wszyscy', max_length=40)),
                ('author', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
