# Generated by Django 2.2 on 2019-07-02 20:17

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Koncert',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nazwa_wydarzenia', models.CharField(max_length=100)),
                ('opis', models.TextField(max_length=500)),
                ('data_start', models.DateTimeField(default='2019-00-00 00:00:00')),
                ('data_koniec', models.DateTimeField(default='2019-00-00 00:00:00')),
                ('miejsce_wydarzenia', models.CharField(max_length=100)),
                ('rodzaj_wydarzenia', models.CharField(choices=[('TK', 'Tydzień Kultury i Nauki'), ('TS', 'Tydzień Sportu'), ('KO', 'Koncerty')], default='KO', max_length=2)),
                ('zdjecie', models.ImageField(default='default.jpg', upload_to='koncert_pics')),
                ('organizator', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
                ('uczestnicy', models.ManyToManyField(blank=True, related_name='participants', to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
