# Generated by Django 2.2 on 2019-07-02 20:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('harmonogram', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='koncert',
            name='miejsce_wydarzenia',
            field=models.CharField(max_length=20),
        ),
    ]
